DATA_DIR   = r"data"
OUTPUT_DIR = r"outputs"

ACTIVITY_MIN_FREQUENCY = 0.10
TOP_N_DRUGS            = 15
TOP_N_PROCEDURES       = 15

AR_MIN_STABLE      = 1
AR_MAX_STABLE      = 5
AR_MIN_FLEXIBLE    = 1
AR_MIN_SUPPORT_PCT = 0.05
AR_MIN_CONFIDENCE  = 0.7

UPLIFT_MAX_DEPTH    = 3
UPLIFT_MIN_LEAF_PCT = 0.05
UPLIFT_MIN_MAX_ITE  = 0.1
