DATA_DIR   = r"data"
OUTPUT_DIR = r"outputs"

ACTIVITY_MIN_FREQUENCY = 0.05

AR_MIN_STABLE      = 1
AR_MIN_FLEXIBLE    = 1
AR_MIN_SUPPORT_PCT = 0.01
AR_MIN_CONFIDENCE  = 0.6
AR_VERBOSE         = False

UPLIFT_MAX_DEPTH    = 5
UPLIFT_MIN_LEAF_PCT = 0.001
UPLIFT_MIN_MAX_ITE  = 0.0
